sudo: false
language: node_js
node_js: 8
before_script:
- npm prune
deploy:
  provider: npm
  email: nlupton@gmx.com
  api_key:
    secure: xQIMKnTu2SYmehrlaGq9lzOnU+Lg4VyljD6sXwBHnvxlA6NfgXFQd3kZHyeQlqr7iaKgZBzWS0PamiGoZwwbVQWGNQn3Hv6nKcM5wPt4ZrwaXaKz5Ur7iqD4p0Rxb64dS2MNLZG5i9rLR1Zs3G+6B/+0ntYteuyxw1jYOyIfrKGs/8xgFod+rZzVidbVaQ+/MCBLnnHRJ9oY5uD+LPyPz5DjkkvYulq+JSHoCGFGocwstu104lET7XfEVFct4izm6E6D4wBUBp1054pnjh4Uk+jVORI7b+FchglatHTTbKiHMXj7Y/f61R9e0JB2xxnKaSVg4oDUANPwZTcacx/ACQQBapo/5GnqlAklowMMt42z6FC51Zim9FTP7bEyQSylyOIdmU8hyRSyyaG7Vx//NHzgVOGPx4+0ZqSzfALKiJ6n4vFZtiC/MQCO2vllw/S30IpzZdPJnaqhJZSk+G5jDXVQB7p7UwnejGCq+PCPm+eTQNEQl1JvWaFws6+B47SGBhefQdGpGaEa/kkM2hohR5lqrLuCCEU7ZJTOvR9Nu4wv0Ia06NI3Z/TIyIt8ozAvq6U0powdgpOPQ8E6pHxGrjtZ4zcrVcDarvuTbTyFUrvz6CPoR9yZv+CjSFoaiV6LDs6uOVq8a4/quWxIw2LGSe/4n0rT1UbncVkHLKXrg8g=
  on:
    repo: Neil188/eslint-config
    branch: master
    tags: true
